version: '3.8'

services:

  orthophonie:
    container_name: orthophonie
    build: .
    ports:
      - "810:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NGINX_RESOLVER=127.0.0.11
    restart: unless-stopped
    networks:
      - ortho_network

networks:
  ortho_network:
    external:
      name: ortho_network